#!/usr/bin/env python3

import os
import shutil
from pathlib import Path

path = os.getcwd()
files = list(file for file in os.listdir(path)
         if os.path.isfile(os.path.join(path, file)))


for f in files:
	name, ext = os.path.splitext(f)
	ext = ext[1:]
	ext_dir = f"{path}/{ext}/"
	file_path = f"{path}/{f}"

	if not ext:
		noext_dir = f"{path}/noextension/"
		Path(noext_dir).mkdir(exist_ok=True)
		shutil.move(file_path, noext_dir)
	else:
		Path(ext_dir).mkdir(exist_ok=True)
		shutil.move(file_path, ext_dir)
